[package]
name = "orion_project1"
version = "0.1.0"
authors = ["alex maslakov <alex@serendipia.email>"]

[dependencies]
hdk = { git = "https://github.com/holochain/holochain-rust", tag = "v0.0.11-alpha1" }

[lib]
path = "src/lib.rs"
